// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	serverservice "go.hollow.sh/serverservice/pkg/api/v1"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BillOfMaterialsBatchUpload mocks base method.
func (m *MockRepository) BillOfMaterialsBatchUpload(ctx context.Context, boms []serverservice.Bom) (*serverservice.ServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BillOfMaterialsBatchUpload", ctx, boms)
	ret0, _ := ret[0].(*serverservice.ServerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BillOfMaterialsBatchUpload indicates an expected call of BillOfMaterialsBatchUpload.
func (mr *MockRepositoryMockRecorder) BillOfMaterialsBatchUpload(ctx, boms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BillOfMaterialsBatchUpload", reflect.TypeOf((*MockRepository)(nil).BillOfMaterialsBatchUpload), ctx, boms)
}

// GetBomInfoByAOCMacAddr mocks base method.
func (m *MockRepository) GetBomInfoByAOCMacAddr(ctx context.Context, macAddr string) (*serverservice.Bom, *serverservice.ServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBomInfoByAOCMacAddr", ctx, macAddr)
	ret0, _ := ret[0].(*serverservice.Bom)
	ret1, _ := ret[1].(*serverservice.ServerResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBomInfoByAOCMacAddr indicates an expected call of GetBomInfoByAOCMacAddr.
func (mr *MockRepositoryMockRecorder) GetBomInfoByAOCMacAddr(ctx, macAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBomInfoByAOCMacAddr", reflect.TypeOf((*MockRepository)(nil).GetBomInfoByAOCMacAddr), ctx, macAddr)
}

// GetBomInfoByBMCMacAddr mocks base method.
func (m *MockRepository) GetBomInfoByBMCMacAddr(ctx context.Context, macAddr string) (*serverservice.Bom, *serverservice.ServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBomInfoByBMCMacAddr", ctx, macAddr)
	ret0, _ := ret[0].(*serverservice.Bom)
	ret1, _ := ret[1].(*serverservice.ServerResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBomInfoByBMCMacAddr indicates an expected call of GetBomInfoByBMCMacAddr.
func (mr *MockRepositoryMockRecorder) GetBomInfoByBMCMacAddr(ctx, macAddr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBomInfoByBMCMacAddr", reflect.TypeOf((*MockRepository)(nil).GetBomInfoByBMCMacAddr), ctx, macAddr)
}
